#!/usr/bin/env python

from argparse import ArgumentParser
from argparse import FileType
import os
import sys
import tpm2


def main():
    parser = ArgumentParser(description='Parse a TPM error code')
    parser.add_argument('rc', type=(lambda x: int(x, 0)))
    args = parser.parse_args()

    pe = tpm2.ProtocolError(None, args.rc)
    print str(pe)

if __name__ == '__main__':
    main()
